spring:
  main:
    banner-mode: off
  codec:
    log-request-details: true
  config:
    activate:
      on-profile: master
  jackson:
    serialization:
      write_dates_as_timestamps: false
  r2dbc:
    url: r2dbc:postgresql://${BREADKUN_DB_URL}/ciabatta
    username: ${BREADKUN_DB_USERNAME}
    password: ${BREADKUN_DB_PASSWORD}
  data:
    mongodb:
      uri: ${BREADKUN_MONGO_DB_URL}/breadkun_db
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

secure:
  ssr-secret-key: ${SSR_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

#logging:
#  level:
#    ROOT: info
#    org.springframework.boot.autoconfigure: warn
#    org.springframework.boot.actuate: warn
#    org.springframework.web: info
#    reactor.netty: warn
#    org.mongodb.driver: warn
#    logging.level.org.springframework.data.r2dbc: warn
#    logging.level.org.springframework.data.mongodb: warn

logging:
  level:
    ROOT: info
    org.springframework.web: debug
    org.springframework.http.codec: debug
    reactor.netty: debug
    org.springframework.data.r2dbc: debug
    org.springframework.data.mongodb: debug