spring:
  application:
    name: ciabatta-core
  profiles:
    active: local-master

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
      base-path: /management

server:
  port: 65477
  servlet:
    encoding:
      charset: UTF-8